# Generated by Django 5.0.6 on 2024-11-27 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('contrasena', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(db_column='idEmpleado', primary_key=True, serialize=False)),
                ('nom_mecanico', models.CharField(max_length=200)),
                ('especialidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_empleado',
            fields=[
                ('id_tipo', models.AutoField(db_column='idTipo', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(db_column='idServicio', primary_key=True, serialize=False)),
                ('nom_servicio', models.CharField(max_length=200)),
                ('duracion_estimada', models.IntegerField()),
                ('empleado', models.ForeignKey(db_column='idEmpleado', on_delete=django.db.models.deletion.CASCADE, to='tallerApp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('hora_servicio', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicio', models.ForeignKey(db_column='idServicio', on_delete=django.db.models.deletion.CASCADE, to='tallerApp.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo',
            field=models.ForeignKey(db_column='idTipo', on_delete=django.db.models.deletion.CASCADE, to='tallerApp.tipo_empleado'),
        ),
    ]
