# Generated by Django 5.0.6 on 2024-11-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='nom_mecanico',
            new_name='nom_empleado',
        ),
    ]
