# Generated by Django 5.0.6 on 2024-11-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallerApp', '0002_rename_nom_mecanico_empleado_nom_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='empleado',
        ),
    ]
