# Generated by Django 5.0.6 on 2024-11-27 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerApp', '0003_remove_servicio_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nombre_c', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nom_producto', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('stock', models.IntegerField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('categoria', models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.CASCADE, to='tallerApp.categoria')),
            ],
        ),
    ]
