# Generated by Django 5.0.6 on 2024-11-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerApp', '0004_categoria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='valor',
            field=models.IntegerField(db_column='valor_servicio', default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.IntegerField(db_column='valor_servicio', verbose_name='Servicio'),
        ),
    ]
