# Generated by Django 5.1.3 on 2024-11-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerApp', '0005_servicio_valor_alter_reserva_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.IntegerField(blank=True, db_column='valor_servicio', null=True, verbose_name='Servicio'),
        ),
    ]
