# Generated by Django 5.1.3 on 2024-11-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerApp', '0006_alter_reserva_precio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contrasena_emp',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='mail_empleado',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
