# Generated by Django 5.1.3 on 2024-11-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerApp', '0007_empleado_contrasena_emp_empleado_mail_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(default='generico', max_length=100),
            preserve_default=False,
        ),
    ]
