# Generated by Django 5.1.3 on 2024-11-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerApp', '0008_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada')], default='pendiente', max_length=10),
        ),
    ]
